# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pods-TestniPod_Tests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pods-TestniPod_Tests

end

target 'TestniPod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestniPod

end
